# MediGuard User Login Details
# Generated by create_dummy_data.py

USERS = [
    {
        "role": "Caretaker",
        "email": "caretaker@mediguard.com",
        "password": "asdfghjkl;'",
        "name": "Samuel Caretaker"
    },
    {
        "role": "User",
        "email": "alice@test.com",
        "password": "asdfghjkl;'",
        "name": "Alice Johnson",
        "caretaker": "caretaker@mediguard.com"
    },
    {
        "role": "User",
        "email": "bob@test.com",
        "password": "asdfghjkl;'",
        "name": "Bob Smith",
        "caretaker": "caretaker@mediguard.com"
    },
    {
        "role": "User",
        "email": "charlie@test.com",
        "password": "asdfghjkl;'",
        "name": "Charlie Davis",
        "caretaker": "caretaker@mediguard.com"
    },
    {
        "role": "User",
        "email": "diana@test.com",
        "password": "asdfghjkl;'",
        "name": "Diana Prince",
        "caretaker": "caretaker@mediguard.com"
    }
]
