import os
import sys
import ast
from pathlib import Path
import fnmatch


def load_ignore_patterns(root_path):
    """Load patterns from .initignore file"""
    ignore_file = root_path / ".initignore"
    patterns = []

    if ignore_file.exists():
        with open(ignore_file, "r") as f:
            for line in f:
                line = line.strip()
                # Skip empty lines and comments
                if line and not line.startswith("#"):
                    patterns.append(line)

    return patterns


def should_ignore(file_path, root_path, patterns):
    """Check if file should be ignored based on patterns"""
    relative_path = file_path.relative_to(root_path)
    rel_path_str = str(relative_path).replace("\\", "/")

    for pattern in patterns:
        # Handle absolute patterns (starting with /)
        if pattern.startswith("/"):
            pattern = pattern[1:]

        # Check if pattern matches
        if fnmatch.fnmatch(rel_path_str, pattern):
            return True
        if fnmatch.fnmatch(file_path.name, pattern):
            return True

    return False


def extract_public_names(file_path):
    """Extract public top-level class and function names from a Python file"""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            tree = ast.parse(f.read())

        names = []
        # Only inspect top-level definitions
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                names.append(node.name)
            elif isinstance(node, ast.FunctionDef) and not node.name.startswith("_"):
                names.append(node.name)

        return sorted(names)
    except Exception as e:
        print(f"Warning: Could not parse {file_path}: {e}")
        return []


def generate_init_file(directory, root_path, ignore_patterns):
    """Generate __init__.py for a directory"""
    init_file = directory / "__init__.py"

    # Check if directory itself should be ignored
    if should_ignore(directory, root_path, ignore_patterns):
        print(f"Skipping (ignored): {directory}")
        return

    imports = []
    all_names = []

    # Find all Python files in directory
    for file_path in sorted(directory.glob("*.py")):
        if file_path.name == "__init__.py":
            continue

        # Check if file should be ignored
        if should_ignore(file_path, root_path, ignore_patterns):
            print(f"  Skipping file (ignored): {file_path.name}")
            continue

        module_name = file_path.stem
        names = extract_public_names(file_path)

        if names:
            imports.append(f"from .{module_name} import {', '.join(names)}")
            all_names.extend(names)
            print(f"  Found in {file_path.name}: {', '.join(names)}")

    # Generate __init__.py content
    if imports:
        content = "# Auto-generated by util.py makeinit\n"
        content += "# Do not edit manually\n\n"
        content += "\n".join(imports)
        content += "\n\n__all__ = [\n"
        content += "\n".join(f"    '{name}'," for name in sorted(all_names))
        content += "\n]\n"

        with open(init_file, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"✓ Generated {init_file.relative_to(root_path)}")
    else:
        # Create empty __init__.py
        with open(init_file, "w", encoding="utf-8") as f:
            f.write("# Auto-generated by util.py makeinit\n")
        print(f"✓ Generated empty {init_file.relative_to(root_path)}")


def makeinit(start_path=None):
    """Generate __init__.py files for all packages"""
    if start_path is None:
        start_path = Path.cwd()
    else:
        start_path = Path(start_path).resolve()

    print(f"Generating __init__.py files in: {start_path}\n")

    # Load ignore patterns
    ignore_patterns = load_ignore_patterns(start_path)
    if ignore_patterns:
        print("Loaded ignore patterns:")
        for pattern in ignore_patterns:
            print(f"  - {pattern}")
        print()

    # Find all directories with Python files
    for dirpath, dirnames, filenames in os.walk(start_path):
        dir_path = Path(dirpath)

        # Skip hidden directories and common non-package directories
        dirnames[:] = [
            d
            for d in dirnames
            if not d.startswith(".")
            and d not in ["__pycache__", "venv", "env", "node_modules"]
        ]

        # Do not create __init__.py in the root path itself
        if dir_path == start_path:
            continue

        # Check if directory has Python files (excluding __init__.py)
        py_files = [f for f in filenames if f.endswith(".py") and f != "__init__.py"]

        if py_files:
            print(f"\nProcessing: {dir_path.relative_to(start_path)}")
            generate_init_file(dir_path, start_path, ignore_patterns)

    print("\n✓ Done!")


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "makeinit":
        # Optional: specify a starting directory
        start_dir = sys.argv[2] if len(sys.argv) > 2 else None
        makeinit(start_dir)
    else:
        print("Usage: uv run util.py makeinit [directory]")
        sys.exit(1)
