# Generated by Django 6.0 on 2026-02-12 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_left', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medicine_photos/')),
                ('type', models.IntegerField(choices=[(0, 'Tablet'), (1, 'Capsule'), (2, 'Syrup'), (3, 'Injection'), (4, 'Other')], default=0)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('dose_per_intake', models.IntegerField(default=1)),
                ('intake_times', models.JSONField(default=list)),
                ('days_of_week', models.JSONField(default=list)),
                ('schedule_alarms', models.BooleanField(default=True)),
                ('alarm_vibrate', models.BooleanField(default=True)),
                ('alarm_snooze_minutes', models.IntegerField(default=5)),
                ('alarm_audio_path', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('alarm_id', models.UUIDField(blank=True, null=True)),
                ('scheduled_time', models.IntegerField()),
                ('actual_taken_time', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Taken'), (2, 'Skipped'), (3, 'Missed')], default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dosage_taken', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='medications.medicine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
