# Generated by Django 6.0 on 2026-01-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareGivers',
        ),
    ]
