# Generated by Django 6.0 on 2026-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregivers',
            old_name='name',
            new_name='nick_name',
        ),
        migrations.AddField(
            model_name='caregivers',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
